#
#	Makefile for bootcamp
#
# Usage:
# make clean  # Clean swap & garbage files

.PHONY = all clean

all:
	@echo "This just saved you from a terrible mistake!"

restart:
	@echo "Removing .tex file, so that .org has clean environment"
	-rm -rvf *.tex
clean:
	@echo "Cleaning up..."
	-rm -rvf *~ \#* \%* *.o
